const images: Record<string, string> = {
  "gigabyte-b760m-ds3h-ddr4": "/products/gigabyte-b760m-ds3h-ddr4.webp",
  "gigabyte-z790-eagle-ddr5": "/products/gigabyte-z790-eagle-ddr5.webp",
  "gigabyte-rtx-5070-windforce": "/products/gigabyte-rtx-5070-windforce.webp",
  "gigabyte-rtx-4060-d6": "/products/gigabyte-rtx-4060-d6.webp",
  "crucial-ddr4-16gb-3200": "/products/crucial-ddr4-16gb-3200.webp",
  "samsung-990-pro-1tb": "/products/samsung-990-pro-1tb.jpg",
  "samsung-870-evo-500gb": "/products/samsung-870-evo-500gb.jpg",
  "gigabyte-aorus-16x": "/products/gigabyte-aorus-16x.webp",
  "gigabyte-g6-mf": "/products/gigabyte-g6-mf.webp",
  "anker-liberty-4-nc": "/products/anker-liberty-4-nc.webp",
  "anker-r50i": "/products/anker-r50i.webp",
  "anker-life-p2-mini": "/products/anker-life-p2-mini.webp",
  "gigabyte-m27q": "/products/gigabyte-m27q.png",
  "gigabyte-g24f-2": "/products/gigabyte-g24f-2.webp",
  "anker-soundcore-motion-plus": "/products/anker-soundcore-motion-plus.webp",
  "gtelk-usb-lan": "/products/gtelk-usb-lan.webp",
  "cooler-master-mwe-gold-650": "/products/cooler-master-mwe-gold-650.jpg",
  "cooler-master-q500l": "/products/cooler-master-q500l.jpg",
  "logitech-mx-mechanical": "/products/logitech-mx-mechanical.jpg",
  "anker-space-q45": "/products/anker-space-q45.jpg",
  "anker-soundcore-go3": "/products/anker-soundcore-go3.jpg",
  "mi-smart-band-10": "/products/mi-smart-band-10.jpg",
  "redmi-watch-5": "/products/redmi-watch-5.jpg",
  "galaxy-watch-7": "/products/galaxy-watch-7.jpg",
  "steelseries-siberia-200": "/products/steelseries-siberia-200.jpg",
  "gigabyte-aorus-h1": "/products/gigabyte-aorus-h1.jpg",
  "gigabyte-aorus-k9": "/products/gigabyte-aorus-k9.jpg",
  "tp-link-archer-ax55": "/products/tp-link-archer-ax55.jpg",
  "tp-link-archer-ax23": "/products/tp-link-archer-ax23.jpg",
  "anker-10000-powerbank": "/products/anker-10000-powerbank.jpg",
  "apple-20w-charger": "/products/apple-20w-charger.jpg",
  "anker-323-33w": "/products/anker-323-33w.webp",
  "anker-737-120w": "/products/anker-737-120w.webp",
  "anker-wireless-charger": "/products/anker-wireless-charger.webp",
};

export function productImageUrl(slug: string): string | null {
  return images[slug] ?? null;
}