services:
  - type: web
    name: avajang-shop
    runtime: node
    plan: free
    buildCommand: npm install && npm install --include=dev && npx prisma db push && npx prisma generate && npx tsx prisma/seed.ts && npm run build
    startCommand: sh -c "next start -p ${PORT:-3000}"
    envVars:
      - key: DATABASE_URL
        value: file:./prisma/dev.db